export const holidays = [
  {
    id: 1,
    title: 'Vienna',
    teaser: 'Dive into the capital of the Habsburg empire',
    description:
      'With a population of almost 2 million, Vienna is the second largest German-speaking city and breathes history in every corner.',
    imageUrl: '/assets/vienna.jpg',
    typeId: 1,
    durationInDays: 3,
    minCount: 5,
    maxCount: 12,
    onSale: true,
    soldOut: false,
  },
  {
    id: 2,
    title: 'London',
    teaser: "Explore one of the world's most famous cities",
    description:
      'Being a tourist magnet, this city needs no further introduction.',
    imageUrl: '/assets/london.jpg',
    typeId: 1,
    durationInDays: 12,
    minCount: 8,
    maxCount: 15,
    onSale: false,
    soldOut: false,
  },
  {
    id: 3,
    title: 'Detroit',
    teaser: 'Top 10 of the cosmopolitan cities of the world',
    description:
      "This US city is mainly known for the autombile industry. It hosts the GM's headquarters.",
    imageUrl: '/assets/detroit.jpg',
    typeId: 2,
    durationInDays: 14,
    minCount: 2,
    maxCount: 10,
    onSale: false,
    soldOut: false,
  },
  {
    id: 4,
    title: 'Reykjavík',
    teaser: 'The northernmost capital of the world and entry to Iceland',
    description:
      'Iceland is a small island between Europe and America. It is best known for its nature and landscape which look almost alien.',
    imageUrl: '/assets/reykjavík.jpg',
    typeId: 1,
    durationInDays: 3,
    minCount: 5,
    maxCount: 15,
    onSale: false,
    soldOut: false,
  },
  {
    id: 6,
    title: 'Shanghai',
    teaser: 'East meets West',
    description:
      'Although not being the capital of China, Shanghai is a good choice to for a China voyage. It can be reached very easily.',
    imageUrl: '/assets/shanghai.jpg',
    typeId: 1,
    durationInDays: 3,
    minCount: 5,
    maxCount: 15,
    onSale: false,
    soldOut: false,
  },
  {
    id: 7,
    title: 'Florence',
    teaser: "Michelangelo's David, da Vinci, and Chianti",
    description:
      'Birthplace of the Renaissance. Many famous artists left their mark. You can marvel at them at the Uffizi Gallery.',
    imageUrl: '/assets/firenze.jpg',
    typeId: 1,
    durationInDays: 3,
    minCount: 5,
    maxCount: 15,
    onSale: false,
    soldOut: false,
  },
  {
    id: 8,
    title: 'Granada',
    teaser: 'Muslim history in Spain',
    description:
      'The Alhambra is not just the major attraction in Granada but also counts to the top must-sees in whole Spain.',
    imageUrl: '/assets/granada.jpg',
    typeId: 1,
    durationInDays: 3,
    minCount: 5,
    maxCount: 15,
    onSale: false,
    soldOut: false,
  },
];
